#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThuVien")]
	public partial class QuanLyThuVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMUONSACH(MUONSACH instance);
    partial void UpdateMUONSACH(MUONSACH instance);
    partial void DeleteMUONSACH(MUONSACH instance);
    partial void InsertSACH(SACH instance);
    partial void UpdateSACH(SACH instance);
    partial void DeleteSACH(SACH instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHELOAI(THELOAI instance);
    partial void UpdateTHELOAI(THELOAI instance);
    partial void DeleteTHELOAI(THELOAI instance);
    partial void InsertTHETV(THETV instance);
    partial void UpdateTHETV(THETV instance);
    partial void DeleteTHETV(THETV instance);
    partial void InsertTHUTHU(THUTHU instance);
    partial void UpdateTHUTHU(THUTHU instance);
    partial void DeleteTHUTHU(THUTHU instance);
    #endregion
		
		public QuanLyThuVienDataContext() : 
				base(global::QuanLyThuVien.Properties.Settings.Default.QuanLyThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MUONSACH> MUONSACHes
		{
			get
			{
				return this.GetTable<MUONSACH>();
			}
		}
		
		public System.Data.Linq.Table<SACH> SACHes
		{
			get
			{
				return this.GetTable<SACH>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THELOAI> THELOAIs
		{
			get
			{
				return this.GetTable<THELOAI>();
			}
		}
		
		public System.Data.Linq.Table<THETV> THETVs
		{
			get
			{
				return this.GetTable<THETV>();
			}
		}
		
		public System.Data.Linq.Table<THUTHU> THUTHUs
		{
			get
			{
				return this.GetTable<THUTHU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MUONSACH")]
	public partial class MUONSACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHE;
		
		private string _MASH;
		
		private string _MATT;
		
		private System.DateTime _NGAYMUON;
		
		private System.Nullable<System.DateTime> _NGAYTRA;
		
		private System.DateTime _HANTRA;
		
		private string _TINHTRANG;
		
		private System.Nullable<decimal> _TIENPHAT;
		
		private string _GHICHU;
		
		private EntityRef<SACH> _SACH;
		
		private EntityRef<THETV> _THETV;
		
		private EntityRef<THUTHU> _THUTHU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHEChanging(string value);
    partial void OnMATHEChanged();
    partial void OnMASHChanging(string value);
    partial void OnMASHChanged();
    partial void OnMATTChanging(string value);
    partial void OnMATTChanged();
    partial void OnNGAYMUONChanging(System.DateTime value);
    partial void OnNGAYMUONChanged();
    partial void OnNGAYTRAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTRAChanged();
    partial void OnHANTRAChanging(System.DateTime value);
    partial void OnHANTRAChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    partial void OnTIENPHATChanging(System.Nullable<decimal> value);
    partial void OnTIENPHATChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public MUONSACH()
		{
			this._SACH = default(EntityRef<SACH>);
			this._THETV = default(EntityRef<THETV>);
			this._THUTHU = default(EntityRef<THUTHU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHE", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHE
		{
			get
			{
				return this._MATHE;
			}
			set
			{
				if ((this._MATHE != value))
				{
					if (this._THETV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHEChanging(value);
					this.SendPropertyChanging();
					this._MATHE = value;
					this.SendPropertyChanged("MATHE");
					this.OnMATHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASH", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASH
		{
			get
			{
				return this._MASH;
			}
			set
			{
				if ((this._MASH != value))
				{
					if (this._SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASHChanging(value);
					this.SendPropertyChanging();
					this._MASH = value;
					this.SendPropertyChanged("MASH");
					this.OnMASHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT", DbType="Char(6)")]
		public string MATT
		{
			get
			{
				return this._MATT;
			}
			set
			{
				if ((this._MATT != value))
				{
					if (this._THUTHU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATTChanging(value);
					this.SendPropertyChanging();
					this._MATT = value;
					this.SendPropertyChanged("MATT");
					this.OnMATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYMUON", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NGAYMUON
		{
			get
			{
				return this._NGAYMUON;
			}
			set
			{
				if ((this._NGAYMUON != value))
				{
					this.OnNGAYMUONChanging(value);
					this.SendPropertyChanging();
					this._NGAYMUON = value;
					this.SendPropertyChanged("NGAYMUON");
					this.OnNGAYMUONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTRA", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTRA
		{
			get
			{
				return this._NGAYTRA;
			}
			set
			{
				if ((this._NGAYTRA != value))
				{
					this.OnNGAYTRAChanging(value);
					this.SendPropertyChanging();
					this._NGAYTRA = value;
					this.SendPropertyChanged("NGAYTRA");
					this.OnNGAYTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HANTRA", DbType="Date NOT NULL")]
		public System.DateTime HANTRA
		{
			get
			{
				return this._HANTRA;
			}
			set
			{
				if ((this._HANTRA != value))
				{
					this.OnHANTRAChanging(value);
					this.SendPropertyChanging();
					this._HANTRA = value;
					this.SendPropertyChanged("HANTRA");
					this.OnHANTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(30)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENPHAT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TIENPHAT
		{
			get
			{
				return this._TIENPHAT;
			}
			set
			{
				if ((this._TIENPHAT != value))
				{
					this.OnTIENPHATChanging(value);
					this.SendPropertyChanging();
					this._TIENPHAT = value;
					this.SendPropertyChanged("TIENPHAT");
					this.OnTIENPHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(MAX)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_MUONSACH", Storage="_SACH", ThisKey="MASH", OtherKey="MASH", IsForeignKey=true)]
		public SACH SACH
		{
			get
			{
				return this._SACH.Entity;
			}
			set
			{
				SACH previousValue = this._SACH.Entity;
				if (((previousValue != value) 
							|| (this._SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SACH.Entity = null;
						previousValue.MUONSACHes.Remove(this);
					}
					this._SACH.Entity = value;
					if ((value != null))
					{
						value.MUONSACHes.Add(this);
						this._MASH = value.MASH;
					}
					else
					{
						this._MASH = default(string);
					}
					this.SendPropertyChanged("SACH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THETV_MUONSACH", Storage="_THETV", ThisKey="MATHE", OtherKey="MATHE", IsForeignKey=true)]
		public THETV THETV
		{
			get
			{
				return this._THETV.Entity;
			}
			set
			{
				THETV previousValue = this._THETV.Entity;
				if (((previousValue != value) 
							|| (this._THETV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THETV.Entity = null;
						previousValue.MUONSACHes.Remove(this);
					}
					this._THETV.Entity = value;
					if ((value != null))
					{
						value.MUONSACHes.Add(this);
						this._MATHE = value.MATHE;
					}
					else
					{
						this._MATHE = default(string);
					}
					this.SendPropertyChanged("THETV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUTHU_MUONSACH", Storage="_THUTHU", ThisKey="MATT", OtherKey="MATT", IsForeignKey=true)]
		public THUTHU THUTHU
		{
			get
			{
				return this._THUTHU.Entity;
			}
			set
			{
				THUTHU previousValue = this._THUTHU.Entity;
				if (((previousValue != value) 
							|| (this._THUTHU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUTHU.Entity = null;
						previousValue.MUONSACHes.Remove(this);
					}
					this._THUTHU.Entity = value;
					if ((value != null))
					{
						value.MUONSACHes.Add(this);
						this._MATT = value.MATT;
					}
					else
					{
						this._MATT = default(string);
					}
					this.SendPropertyChanged("THUTHU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SACH")]
	public partial class SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASH;
		
		private string _TENSH;
		
		private string _MALOAI;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _NXB;
		
		private System.Nullable<int> _NAMXB;
		
		private string _TACGIA;
		
		private System.Nullable<double> _GIA;
		
		private EntitySet<MUONSACH> _MUONSACHes;
		
		private EntityRef<THELOAI> _THELOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASHChanging(string value);
    partial void OnMASHChanged();
    partial void OnTENSHChanging(string value);
    partial void OnTENSHChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnNXBChanging(string value);
    partial void OnNXBChanged();
    partial void OnNAMXBChanging(System.Nullable<int> value);
    partial void OnNAMXBChanged();
    partial void OnTACGIAChanging(string value);
    partial void OnTACGIAChanged();
    partial void OnGIAChanging(System.Nullable<double> value);
    partial void OnGIAChanged();
    #endregion
		
		public SACH()
		{
			this._MUONSACHes = new EntitySet<MUONSACH>(new Action<MUONSACH>(this.attach_MUONSACHes), new Action<MUONSACH>(this.detach_MUONSACHes));
			this._THELOAI = default(EntityRef<THELOAI>);
			OnCreated();
		}
        public override string ToString()
        {
            return this._MASH + " - " + this._TENSH;
        }
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASH", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASH
		{
			get
			{
				return this._MASH;
			}
			set
			{
				if ((this._MASH != value))
				{
					this.OnMASHChanging(value);
					this.SendPropertyChanging();
					this._MASH = value;
					this.SendPropertyChanged("MASH");
					this.OnMASHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSH", DbType="NVarChar(30)")]
		public string TENSH
		{
			get
			{
				return this._TENSH;
			}
			set
			{
				if ((this._TENSH != value))
				{
					this.OnTENSHChanging(value);
					this.SendPropertyChanging();
					this._TENSH = value;
					this.SendPropertyChanged("TENSH");
					this.OnTENSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(6)")]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._THELOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NXB", DbType="NVarChar(30)")]
		public string NXB
		{
			get
			{
				return this._NXB;
			}
			set
			{
				if ((this._NXB != value))
				{
					this.OnNXBChanging(value);
					this.SendPropertyChanging();
					this._NXB = value;
					this.SendPropertyChanged("NXB");
					this.OnNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMXB", DbType="Int")]
		public System.Nullable<int> NAMXB
		{
			get
			{
				return this._NAMXB;
			}
			set
			{
				if ((this._NAMXB != value))
				{
					this.OnNAMXBChanging(value);
					this.SendPropertyChanging();
					this._NAMXB = value;
					this.SendPropertyChanged("NAMXB");
					this.OnNAMXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TACGIA", DbType="NVarChar(30)")]
		public string TACGIA
		{
			get
			{
				return this._TACGIA;
			}
			set
			{
				if ((this._TACGIA != value))
				{
					this.OnTACGIAChanging(value);
					this.SendPropertyChanging();
					this._TACGIA = value;
					this.SendPropertyChanged("TACGIA");
					this.OnTACGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Float")]
		public System.Nullable<double> GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_MUONSACH", Storage="_MUONSACHes", ThisKey="MASH", OtherKey="MASH")]
		public EntitySet<MUONSACH> MUONSACHes
		{
			get
			{
				return this._MUONSACHes;
			}
			set
			{
				this._MUONSACHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_SACH", Storage="_THELOAI", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public THELOAI THELOAI
		{
			get
			{
				return this._THELOAI.Entity;
			}
			set
			{
				THELOAI previousValue = this._THELOAI.Entity;
				if (((previousValue != value) 
							|| (this._THELOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THELOAI.Entity = null;
						previousValue.SACHes.Remove(this);
					}
					this._THELOAI.Entity = value;
					if ((value != null))
					{
						value.SACHes.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(string);
					}
					this.SendPropertyChanged("THELOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MUONSACHes(MUONSACH entity)
		{
			this.SendPropertyChanging();
			entity.SACH = this;
		}
		
		private void detach_MUONSACHes(MUONSACH entity)
		{
			this.SendPropertyChanging();
			entity.SACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDN;
		
		private string _MATKHAU;
		
		private string _EMAIL;
		
		private System.Nullable<int> _QUYEN;
		
		private EntitySet<THUTHU> _THUTHUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnQUYENChanging(System.Nullable<int> value);
    partial void OnQUYENChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._THUTHUs = new EntitySet<THUTHU>(new Action<THUTHU>(this.attach_THUTHUs), new Action<THUTHU>(this.detach_THUTHUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="Int")]
		public System.Nullable<int> QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_THUTHU", Storage="_THUTHUs", ThisKey="TENDN", OtherKey="TENDN")]
		public EntitySet<THUTHU> THUTHUs
		{
			get
			{
				return this._THUTHUs;
			}
			set
			{
				this._THUTHUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THUTHUs(THUTHU entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_THUTHUs(THUTHU entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THELOAI")]
	public partial class THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAI;
		
		private string _TENLOAI;
		
		private EntitySet<SACH> _SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    #endregion
		
		public THELOAI()
		{
			this._SACHes = new EntitySet<SACH>(new Action<SACH>(this.attach_SACHes), new Action<SACH>(this.detach_SACHes));
			OnCreated();
		}
        public override string ToString()
        {
            return this._MALOAI + " - " + this._TENLOAI;
        }
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(50)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_SACH", Storage="_SACHes", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<SACH> SACHes
		{
			get
			{
				return this._SACHes;
			}
			set
			{
				this._SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = this;
		}
		
		private void detach_SACHes(SACH entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THETV")]
	public partial class THETV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHE;
		
		private string _TENDG;
		
		private string _PHAI;
		
		private string _SODT;
		
		private string _DIACHI;
		
		private System.Nullable<System.DateTime> _NGAYCAP;
		
		private System.Nullable<System.DateTime> _NGAYHETHAN;
		
		private System.Data.Linq.Binary _ANHTHE;
		
		private EntitySet<MUONSACH> _MUONSACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHEChanging(string value);
    partial void OnMATHEChanged();
    partial void OnTENDGChanging(string value);
    partial void OnTENDGChanged();
    partial void OnPHAIChanging(string value);
    partial void OnPHAIChanged();
    partial void OnSODTChanging(string value);
    partial void OnSODTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnNGAYCAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPChanged();
    partial void OnNGAYHETHANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYHETHANChanged();
    partial void OnANHTHEChanging(System.Data.Linq.Binary value);
    partial void OnANHTHEChanged();
    #endregion
		
		public THETV()
		{
			this._MUONSACHes = new EntitySet<MUONSACH>(new Action<MUONSACH>(this.attach_MUONSACHes), new Action<MUONSACH>(this.detach_MUONSACHes));
			OnCreated();
		}
        public override string ToString()
        {
            return this._MATHE + " - " + this._TENDG;
        }
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHE", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHE
		{
			get
			{
				return this._MATHE;
			}
			set
			{
				if ((this._MATHE != value))
				{
					this.OnMATHEChanging(value);
					this.SendPropertyChanging();
					this._MATHE = value;
					this.SendPropertyChanged("MATHE");
					this.OnMATHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDG", DbType="NVarChar(30)")]
		public string TENDG
		{
			get
			{
				return this._TENDG;
			}
			set
			{
				if ((this._TENDG != value))
				{
					this.OnTENDGChanging(value);
					this.SendPropertyChanging();
					this._TENDG = value;
					this.SendPropertyChanged("TENDG");
					this.OnTENDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAI", DbType="NVarChar(3)")]
		public string PHAI
		{
			get
			{
				return this._PHAI;
			}
			set
			{
				if ((this._PHAI != value))
				{
					this.OnPHAIChanging(value);
					this.SendPropertyChanging();
					this._PHAI = value;
					this.SendPropertyChanged("PHAI");
					this.OnPHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODT", DbType="Char(10)")]
		public string SODT
		{
			get
			{
				return this._SODT;
			}
			set
			{
				if ((this._SODT != value))
				{
					this.OnSODTChanging(value);
					this.SendPropertyChanging();
					this._SODT = value;
					this.SendPropertyChanged("SODT");
					this.OnSODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(30)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHETHAN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYHETHAN
		{
			get
			{
				return this._NGAYHETHAN;
			}
			set
			{
				if ((this._NGAYHETHAN != value))
				{
					this.OnNGAYHETHANChanging(value);
					this.SendPropertyChanging();
					this._NGAYHETHAN = value;
					this.SendPropertyChanged("NGAYHETHAN");
					this.OnNGAYHETHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANHTHE", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ANHTHE
		{
			get
			{
				return this._ANHTHE;
			}
			set
			{
				if ((this._ANHTHE != value))
				{
					this.OnANHTHEChanging(value);
					this.SendPropertyChanging();
					this._ANHTHE = value;
					this.SendPropertyChanged("ANHTHE");
					this.OnANHTHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THETV_MUONSACH", Storage="_MUONSACHes", ThisKey="MATHE", OtherKey="MATHE")]
		public EntitySet<MUONSACH> MUONSACHes
		{
			get
			{
				return this._MUONSACHes;
			}
			set
			{
				this._MUONSACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MUONSACHes(MUONSACH entity)
		{
			this.SendPropertyChanging();
			entity.THETV = this;
		}
		
		private void detach_MUONSACHes(MUONSACH entity)
		{
			this.SendPropertyChanging();
			entity.THETV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUTHU")]
	public partial class THUTHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATT;
		
		private string _HOTEN;
		
		private string _PHAI;
		
		private string _DIACHI;
		
		private string _SODT;
		
		private string _TENDN;
		
		private EntitySet<MUONSACH> _MUONSACHes;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATTChanging(string value);
    partial void OnMATTChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnPHAIChanging(string value);
    partial void OnPHAIChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSODTChanging(string value);
    partial void OnSODTChanged();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    #endregion
		
		public THUTHU()
		{
			this._MUONSACHes = new EntitySet<MUONSACH>(new Action<MUONSACH>(this.attach_MUONSACHes), new Action<MUONSACH>(this.detach_MUONSACHes));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATT
		{
			get
			{
				return this._MATT;
			}
			set
			{
				if ((this._MATT != value))
				{
					this.OnMATTChanging(value);
					this.SendPropertyChanging();
					this._MATT = value;
					this.SendPropertyChanged("MATT");
					this.OnMATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAI", DbType="NVarChar(3)")]
		public string PHAI
		{
			get
			{
				return this._PHAI;
			}
			set
			{
				if ((this._PHAI != value))
				{
					this.OnPHAIChanging(value);
					this.SendPropertyChanging();
					this._PHAI = value;
					this.SendPropertyChanged("PHAI");
					this.OnPHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODT", DbType="Char(10)")]
		public string SODT
		{
			get
			{
				return this._SODT;
			}
			set
			{
				if ((this._SODT != value))
				{
					this.OnSODTChanging(value);
					this.SendPropertyChanging();
					this._SODT = value;
					this.SendPropertyChanged("SODT");
					this.OnSODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(30)")]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUTHU_MUONSACH", Storage="_MUONSACHes", ThisKey="MATT", OtherKey="MATT")]
		public EntitySet<MUONSACH> MUONSACHes
		{
			get
			{
				return this._MUONSACHes;
			}
			set
			{
				this._MUONSACHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_THUTHU", Storage="_TAIKHOAN", ThisKey="TENDN", OtherKey="TENDN", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.THUTHUs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.THUTHUs.Add(this);
						this._TENDN = value.TENDN;
					}
					else
					{
						this._TENDN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MUONSACHes(MUONSACH entity)
		{
			this.SendPropertyChanging();
			entity.THUTHU = this;
		}
		
		private void detach_MUONSACHes(MUONSACH entity)
		{
			this.SendPropertyChanging();
			entity.THUTHU = null;
		}
	}
}
#pragma warning restore 1591
